---
# tasks file for squid (Debian specific)

- name: Install squid packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ squid_packages }}"
  tags:
    - squid
